In [5]:
import cv2;
print("Original Image")
image = cv2.imread("shakiliitju.jpg")
image


print("Gray Sale Image")
image1 = cv2.imread("shakiliitju.jpg",0)
image1
cv2.imwrite("My_Image.png",image1)



Original Image
Gray Sale Image


True

## Image Print

In [6]:
import cv2
image = cv2.imread("shakiliitju.jpg")
image

from numpy import asarray
data = asarray(image)
print(data)

[[[ 34  72 130]
  [ 49  87 145]
  [ 47  85 143]
  ...
  [109 144 194]
  [104 139 189]
  [ 88 123 173]]

 [[ 39  77 135]
  [ 52  90 148]
  [ 45  83 141]
  ...
  [104 139 189]
  [105 140 190]
  [ 83 118 168]]

 [[ 48  86 144]
  [ 61  99 157]
  [ 45  83 141]
  ...
  [103 138 188]
  [109 144 194]
  [ 89 124 174]]

 ...

 [[ 88 117 156]
  [ 92 121 160]
  [ 94 119 161]
  ...
  [103 139 187]
  [107 140 189]
  [117 150 199]]

 [[ 88 117 156]
  [ 89 118 157]
  [ 92 117 159]
  ...
  [103 139 187]
  [106 139 188]
  [115 148 197]]

 [[ 93 122 161]
  [ 88 117 156]
  [ 87 112 154]
  ...
  [101 137 185]
  [104 137 186]
  [112 145 194]]]


## Image Rotation



In [7]:
import cv2
import imutils
image = cv2.imread("shakiliitju.jpg")
image
print("Rotated Image")
print("45 degree angle rotation")
R1=imutils.rotate(image, 180)
R1


Rotated Image
45 degree angle rotation


array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [112, 145, 194],
        [104, 137, 186],
        ...,
        [ 87, 112, 154],
        [ 87, 112, 154],
        [ 88, 117, 156]],

       [[  0,   0,   0],
        [115, 148, 197],
        [106, 139, 188],
        ...,
        [ 85, 110, 152],
        [ 92, 117, 159],
        [ 89, 118, 157]],

       ...,

       [[  0,   0,   0],
        [ 97, 132, 182],
        [108, 143, 193],
        ...,
        [ 69, 107, 165],
        [ 44,  82, 140],
        [ 64, 102, 160]],

       [[  0,   0,   0],
        [ 89, 124, 174],
        [109, 144, 194],
        ...,
        [ 64, 102, 160],
        [ 45,  83, 141],
        [ 61,  99, 157]],

       [[  0,   0,   0],
        [ 83, 118, 168],
        [105, 140, 190],
        ...,
        [ 68, 106, 164],
        [ 45,  83, 141],
        [ 52,  90, 148]]

## RGB to CMY Convention

In [8]:
import cv2
print("Original Image")
image = cv2.imread("shakiliitju.jpg")
image
print("RGB Image")
R,G,B = cv2.split(image)
print("R")
R

print("G")
G

print("B")
B


C=1-R
M=1-G
Y=1-B
print("CMY image")
print("C Complacent")
C

print("C Complacent")
M

print("C Complacent")
Y

Original Image
RGB Image
R
G
B
CMY image
C Complacent
C Complacent
C Complacent


array([[127, 112, 114, ...,  63,  68,  84],
       [122, 109, 116, ...,  68,  67,  89],
       [113, 100, 116, ...,  69,  63,  83],
       ...,
       [101,  97,  96, ...,  70,  68,  58],
       [101, 100,  98, ...,  70,  69,  60],
       [ 96, 101, 103, ...,  72,  71,  63]], dtype=uint8)